### ISSUE TITLE
新手

### ISSUE THREAD

**Issue by OUC2022** [summitgao/SAR_CD_GDNet#1]
刚刚入门GitHub，奔海大而来，果然遇到了比较活跃的高教授，知乎也有关注，本条评论不是提问，是留下足迹。【勿怪...】

**Comment by OUC2022** [comment]
> 刚刚入门GitHub，奔海大而来，果然遇到了比较活跃的高教授，知乎也有关注，本条评论不是提问，是留下足迹。【勿怪...】

补充：新年快乐！科研事业进步

**Comment by summitgao** [comment]
太客气了，新年快乐！
